# Generated by Django 4.0.1 on 2022-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmyWebApp', '0005_alter_dodatkoweinfo_gatunek_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (4, 'Dramat'), (0, 'Inne')], default=0),
        ),
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='FilmyWebApp.Film')),
            ],
        ),
    ]
